CREATE TABLE digi_flow_schema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slug VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL DEFAULT 'Unnamed Schema',
    yaml_schema TEXT,
    schema JSONB NOT NULL DEFAULT '{}'::jsonb,
    version INT NOT NULL DEFAULT 1,
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'UTC'),
    created_by JSONB,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by JSONB,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by JSONB,
    PRIMARY KEY (id, version)
);

CREATE UNIQUE INDEX idx_digi_flow_schema_active_slug
    ON digi_flow_schema (slug, version) WHERE deleted_at IS NULL;

CREATE TABLE digi_flow_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slug VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description TEXT,
    domain VARCHAR(64),
    schema_id BIGINT NOT NULL,
    schema_version INT NOT NULL,
    source_content_type INT NOT NULL,
    workflow_config JSONB,
    prompt_config JSONB,
    schema_validation JSONB,
    version INT NOT NULL DEFAULT 1,
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'UTC'),
    created_by JSONB,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by JSONB,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by JSONB,
    PRIMARY KEY (id, version)
);

CREATE TABLE digi_flow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id BIGINT NOT NULL,
    config_version INT NOT NULL,
    schema_id BIGINT NOT NULL,
    schema_version INT NOT NULL,
    content_type INT NOT NULL,
    content_context JSONB NOT NULL DEFAULT '{}'::jsonb,
    content_metadata JSONB,
    langsmith_trace_id VARCHAR,
    langsmith_metadata JSONB,
    main_status INT NOT NULL DEFAULT 0,
    data_service_status INT NOT NULL DEFAULT 0,
    schema_validation_status INT NOT NULL DEFAULT 0,
    schema_validation_result JSONB,
    extra_attributes JSONB,
    metadata JSONB,
    is_sampled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'UTC'),
    created_by JSONB,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by JSONB
);

CREATE INDEX idx_digi_flow_config_version ON digi_flow (config_id, config_version);
CREATE INDEX idx_digi_flow_main_status ON digi_flow (main_status);

CREATE TABLE digi_flow_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_id BIGINT NOT NULL,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    plain_data JSONB,
    text_blocks JSONB,
    data_origin INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 1,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'UTC'),
    updated_by JSONB
);

CREATE UNIQUE INDEX idx_digi_flow_result_flow_id_version ON digi_flow_result (flow_id, version);

CREATE TABLE rag_training_data_vector (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_id BIGINT NOT NULL,
    config_id BIGINT NOT NULL,
    schema_id BIGINT NOT NULL,
    schema_version INT NOT NULL,
    result_id BIGINT NOT NULL,
    result_version INT NOT NULL,
    source_content_context JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_content_context_idx INT NOT NULL DEFAULT 0,
    reference_input JSONB NOT NULL,
    reference_output JSONB NOT NULL,
    embedding VECTOR(1536) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc'),
    created_by JSONB
);

CREATE INDEX idx_rag_training_data_vector_embedding_hnsw
    ON rag_training_data_vector USING hnsw (embedding vector_cosine_ops);

CREATE INDEX idx_rag_training_data_vector_config_id
    ON rag_training_data_vector (config_id, flow_id);

CREATE UNIQUE INDEX idx_rag_training_data_vector_flow_id_source_content_context_idx
    ON rag_training_data_vector (flow_id, source_content_context_idx);

CREATE TABLE digi_flow_result_field_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_id BIGINT NOT NULL,
    result_id BIGINT NOT NULL,
    result_version INT NOT NULL,
    field_path TEXT NOT NULL,
    old_value JSONB,
    new_value JSONB,
    reason_code INT NOT NULL,
    reason_text TEXT,
    audited_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'UTC'),
    audited_by JSONB
);
